version: '3.8'

services:
  receipt-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - CONFIG_FILE=config.json
    restart: unless-stopped
